name: Sunflower Web Design
favicon: null
layout_spectrum: 0.7330424122046679
typography_spectrum: 0.8708995864726603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07577374204993248
  lightness: 0.6032637173775584
  saturation: 0.32213787524960935
  rhythmicContrast: 0.4185506082139909
purpose: []
